export const dom = {
  themeToggle: document.getElementById('theme-toggle'),
  search: document.getElementById('search-input'),
  clearSearch: document.getElementById('clear-search'),
  cartToggle: document.getElementById('cart-toggle'),
  cartCount: document.getElementById('cart-count'),

  categorySelect: document.getElementById('category-select'),
  priceRange: document.getElementById('price-range'),
  priceDisplay: document.getElementById('price-display'),
  ratingFilters: document.getElementById('rating-filters'),
  sortSelect: document.getElementById('sort-select'),
  resetFilters: document.getElementById('reset-filters'),

  productsGrid: document.getElementById('products-grid'),
  resultsCount: document.getElementById('results-count'),
  activeFilters: document.getElementById('active-filters'),
  cartCheckout: document.getElementById('cart-checkout'),
  cartTotal: document.getElementById('cart-total'),
  buyCartBtn: document.getElementById('buy-cart-btn'),
  pagination: document.getElementById('pagination'),
  emptyState: document.getElementById('empty-state'),
  emptyClearBtn: document.getElementById('empty-clear-btn'),
  footer: document.querySelector('.footer'),

  modal: document.getElementById('product-modal'),
  modalClose: document.getElementById('modal-close'),
  modalImg: document.getElementById('modal-image'),
  modalCat: document.getElementById('modal-category'),
  modalName: document.getElementById('modal-name'),
  modalDesc: document.getElementById('modal-description'),
  modalPrice: document.getElementById('modal-price'),
  modalRating: document.getElementById('modal-rating-text'),
  modalTags: document.getElementById('modal-tags'),
  interactiveStars: document.getElementById('interactive-stars'),
  ratingFeedback: document.getElementById('rating-feedback'),
  modalCartBtn: document.getElementById('modal-cart-btn'),
  modalCartText: document.getElementById('modal-cart-text'),
  modalBuy: document.getElementById('modal-buy'),

  toastContainer: document.getElementById('toast-container'),
  scrollCatalog: document.getElementById('scroll-catalog'),
  mobileMenuBtn: document.getElementById('mobile-menu-btn'),
  headerMenu: document.getElementById('header-menu')
};
